### ISSUE TITLE
OTLP Output Operator

### ISSUE THREAD

**Issue by djaglowski** [observIQ/stanza#130]
**Is your feature request related to a problem? Please describe.**
The standalone stanza agent does not have a way to emit logs over network to an OpenTelemetry collector.

**Describe the solution you'd like**
Stanza should implement an OTLP output operator, which sends to an OpenTelemetry OTLP receiver.

**Additional context**
This will be useful in some kubernetes deployments.

**Comment by camdencheek** [comment]
Marking this done -- merged in #173
