### ISSUE TITLE
Plugin Metadata - Min and Max Stanza Version

### ISSUE THREAD

**Issue by djaglowski** [observIQ/stanza#140]
**Is your feature request related to a problem? Please describe.**
As stanza evolves, older plugins occasionally require updates. However, it is not always clear which versions of stanza a plugin has been validated against. Allowing plugin developers to specify a min or max version of stanza would provide some clarity on whether the plugin can be used.

**Describe the solution you'd like**
- Add min and max version fields to plugin metadata.
- When loading a plugin, validate the current version of stanza against the min and/or max version.

**Comment by camdencheek** [comment]
Fixed by #172
