### ISSUE TITLE
stanza_input should allow configuration of log level

### ISSUE THREAD

**Issue by djaglowski** [observIQ/stanza#177]
Since it is not always convenient to modify how stanza is run, we should allow the operator itself to define the log level.

**Comment by camdencheek** [comment]
@djaglowski This one is a bit harder than it sounds. The global log level is set before the stanza input operator is ever created. Additionally, the logs are filtered by level before they ever make it to the operator. Zap checks whether it should write the log before sending it, so if the global log level is `info`, the stanza input operator won't ever see `debug` logs

**Comment by djaglowski** [comment]
We'll reopen this if we can determine a reasonable design alternative.
