### ISSUE TITLE
Linux install - Service already exists prompt does not wait for user input

### ISSUE THREAD

**Issue by djaglowski** [observIQ/stanza#178]
```
===================================================
| Creating Service
===================================================
  Service 'stanza' already exists. Replace it? [y]/n:     Replacing service!
  Creating service file...
```

**Environment:**
 - Observed on Amazon Linux

**Comment by camdencheek** [comment]
Could not reproduce on Debian 10. Setting up an Amazon Linux box now

**Comment by camdencheek** [comment]
@djaglowski I'm unable to reproduce this on Amazon Linux. Is there anything else about the environment that might have caused this?

**Comment by djaglowski** [comment]
@camdencheek Thanks for looking into it. I don't know what else might have been relevant. Will close for now.
