### ISSUE TITLE
Support float64 for severity parsing

### ISSUE THREAD

**Issue by jsirianni** [observIQ/stanza#267]
**Is your feature request related to a problem? Please describe.**

Parsing the severity using the `pri` field will not work, because json numbers are decoded as float64 values. 

```
{
  "uid": 62,
  "time": 1617410898,
  "pri": 6,
  "tag": "pve-ha-lrm",
  "pid": 33690,
  "node": "pve-1",
  "user": "root@pam",
  "msg": "end task UPID:pve-1:0000839B:000C5C3F:6067BB15:qmshutdown:100:root@pam: OK"
}
```

I can resolve this with a quick patch to `operator/helper/severity.go`, however, my solution is not production ready
```
func (m severityMap) find(value interface{}) (entry.Severity, string, error) {
	switch v := value.(type) {
	case int:
		strV := strconv.Itoa(v)
		if severity, ok := m[strV]; ok {
			return severity, strV, nil
		}
		return entry.Default, strV, nil
	case float64:
		strV := strconv.Itoa(int(v))
		if severity, ok := m[strV]; ok {
			return severity, strV, nil
		}
		return entry.Default, strV, nil
...
```

This works great for my example, will perform incorrectly when the value being parsed is actually a float64.

**Describe the solution you'd like**

The ability to handle float64 with an optional `precision` parameter would be nice.

For example, if the `pri` value is `6.5`, my solution would return 6, which may not be acceptable.

**Describe alternatives you've considered**

An operator for converting a value's type could be used instead. This would allow the user to convert from float64 to a string or int. Some control over the precision would still be required. I think this operator would be useful in general, but very clunky for solving this specific problem.

**Comment by djaglowski** [comment]
I haven't seen any use cases where a numeric severity is actually meant to be a float value, so my opinion is that we can cast it to int as you've shown.

There's been discussion about a type conversion operator before, and I think we probably do need this at some point. Someone needs to spec out what it would be capable of, how it is configured, how it handles various error scenarios, etc.
