### ISSUE TITLE
Stanza fails to install on macOS 

### ISSUE THREAD

**Issue by ryancgoins** [observIQ/stanza#543]
**Describe the bug**
When installing Stanza on macOS using the single-line installer the installation fails when "Setting Permissions" with the exception `ln: /usr/local/bin/stanza: No such file or directory`. 

This is on an M1 MacBook Pro running macOS 12.2

**To Reproduce**
1. Run the installer script `sh -c "$(curl -fsSlL https://github.com/observiq/stanza/releases/latest/download/unix-install.sh)" unix-install.sh` on macOS 

**Expected behavior**
The installation to complete successfully and stanza to start

**Screenshots**
<img width="684" alt="Screen Shot 2022-02-09 at 2 21 26 PM" src="https://user-images.githubusercontent.com/99215045/153664441-25f44f9c-6c97-4cd3-a0cc-8cc89df51038.png">

**Environment:**
 - OS: macOS 12.2 M1
 - Stanza Version 1.5.5
.

**Comment by Dylan-M** [comment]
Not actually a bug, confirmed with Ryan that he just forgot `sudo`
