### ISSUE TITLE
Stanza Timestamp parsing doesn't support parsing "Z" as "UTC"

### ISSUE THREAD

**Issue by Mrod1598** [observIQ/stanza#574]
**Is your feature request related to a problem? Please describe.**
Update Timestamp parsing to support Timestamps in the form of 
`2022-01-17T18:31:47,365Z`

**Describe the solution you'd like**
Probably will involve updating our fork of the time parsing package we use.

**Comment by BinaryFissionGames** [comment]
Is this true even with "layout_type" set to "gotime"? I feel like I've had the native go library do this type of time parsing just fine.
